FROM python:3.12-slim

WORKDIR /app

COPY requirements-query.txt .
RUN pip install --no-cache-dir -r requirements-query.txt

COPY query_service/ ./query_service/
COPY shared/ ./shared/

ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "query_service.serve_app"]