apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluesky-firehose-consumer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://github.com/g-clef/bluesky_consumer
    targetRevision: main
    path: kubernetes/firehose-consumer

  destination:
    server: https://kubernetes.default.svc
    namespace: bluesky

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas