apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluesky-namespace
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default

  source:
    repoURL: https://github.com/g-clef/bluesky_consumer
    targetRevision: main
    path: kubernetes
    directory:
      include: namespace.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: bluesky

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true